#!/bin/bash

# ---------- BEGIN ---------- 

export DOTFILES_PATH=$HOME/.config
export DOTFILES_GIT=$HOME/Documents/GitHub/dotfiles

# -- i3 directory
cp -uvr $DOTFILES_PATH/i3/ $DOTFILES_GIT/.config/

# -- scripts directory
cp -uvr ~/Scripts/* $DOTFILES_GIT/scripts

# -- termite directory
cp -uvr $DOTFILES_PATH/termite/ $DOTFILES_GIT/.config/

# -- gtk-3.0 directory
cp -uvr $DOTFILES_PATH/gtk-3.0/ $DOTFILES_GIT/.config/

# -- cheat directory
cp -uvr ~/.config/cheat $DOTFILES_GIT/.config/

# -- hangups directory
cp -uvr $DOTFILES_PATH/hangups $DOTFILES_GIT/.config/

# -- ncmpcpp directory
cp -uvr $DOTFILES_PATH/ncmpcpp $DOTFILES_GIT/.config/

# -- mpd config file
cp -uv $DOTFILES_PATH/mpd/mpd.conf $DOTFILES_GIT/.config/mpd/mpd.conf

# -- bumblebee theme & custom modules
cp -uv $DOTFILES_PATH/bumblebee/themes/turing.json $DOTFILES_GIT/.config/bumblebee/turing.json
cp -uv $DOTFILES_PATH/bumblebee/bumblebee/modules/brightness.py $DOTFILES_GIT/.config/bumblebee/brightness.py

# -- tmux config file
cp -uv $DOTFILES_PATH/tmux/.tmux.conf $DOTFILES_GIT/.config/tmux/.tmux.conf

# -- vim config file
cp -uv ~/.vimrc $DOTFILES_GIT/.vimrc

## -- emacs config file
cp -uv ~/.emacs $DOTFILES_GIT/.emacs

# -- ranger config file & scripts
cp -uv $DOTFILES_PATH/ranger/rc.conf $DOTFILES_GIT/.config/ranger/rc.conf
cp -uv $DOTFILES_PATH/ranger/rifle.conf $DOTFILES_GIT/.config/ranger/rifle.conf
cp -uv $DOTFILES_PATH/ranger/scope.sh $DOTFILES_GIT/.config/ranger/scope.sh
cp -uv $DOTFILES_PATH/ranger/commands.py $DOTFILES_GIT/.config/ranger/commands.py
cp -uv $DOTFILES_PATH/ranger/commands_full.py $DOTFILES_GIT/.config/ranger/commands_full.py

# -- compton config file
cp -uv $DOTFILES_PATH/compton.conf $DOTFILES_GIT/.config/compton.conf

# -- cava config file
cp -uv $DOTFILES_PATH/cava/config $DOTFILES_GIT/.config/cava/config

# -- neofetch config file
cp -uv $DOTFILES_PATH/neofetch/config $DOTFILES_GIT/.config/neofetch/config

# -- Xresources config file
cp -uv ~/.Xresources $DOTFILES_GIT/.Xresources

# -- Xsession config file
cp -uv ~/.xsessionrc $DOTFILES_GIT/.xsessionrc

# -- font config file
cp -uv ~/.fonts.conf $DOTFILES_GIT/.fonts.conf

# -- zsh config file
cp -uv ~/.zshrc $DOTFILES_GIT/.zshrc

# -- rainbowstream config file
cp -uv ~/.rainbow_config.json $DOTFILES_GIT/.rainbow_config.json

# -- the script itself
cp -uv ~/Scripts/sc-update-dotfiles $DOTFILES_GIT/scripts/sc-update-dotfiles

# ---------- END ----------
